# Generated by Django 4.0.4 on 2022-05-30 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_post_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create_data',
            new_name='create_date',
        ),
    ]
